### ISSUE TITLE
Add timestamp to onscreen output

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/Gigvaision-ControlSoftware#34]
Can you append a time-stamp to all outputs on the gigavision camera? would be helpful so I can glacne at the screen and see when it last did something (i.e. if it is working). If this is a hassle, at least adding it to the error messages and at the end/start of each capture session would be helpful.

Thanks

**Comment by gdunstone** [comment]
Yep.

**Comment by chuong** [comment]
This is done.
